import { StyleSheet } from "react-native";
export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f8f9f5" },
  flex: { flex: 1 },
  header: {
    paddingHorizontal: 22,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    borderBottomColor: "#e8ebdf",
    borderBottomWidth: 1,
  },
  logo: {
    fontSize: 39,
    fontWeight: "900",
    letterSpacing: -2,
    color: "#262b20",
  },
  logoDot: { color: "#e6ba2f" },
  login: { backgroundColor: "#ffdb55", padding: 11, borderRadius: 8 },
  loginText: { fontSize: 14, fontWeight: "600" },
  feed: { padding: 15 },
  eyebrow: { fontSize: 12, color: "#899478", letterSpacing: 1, marginTop: 10 },
  heading: {
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: -1,
    marginTop: 10,
    marginBottom: 17,
    color: "#292e21",
  },
  searchRow: { flexDirection: "row", gap: 8 },
  searchButton: {
    backgroundColor: "#ecefdf",
    padding: 13,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  input: {
    borderWidth: 1,
    borderColor: "#dfe5d4",
    borderRadius: 9,
    padding: 13,
    backgroundColor: "#fff",
    fontSize: 15,
    marginBottom: 13,
    color: "#292f21",
  },
  tabs: { flexDirection: "row", gap: 8, marginBottom: 16 },
  tab: { padding: 11, borderRadius: 8 },
  tabActive: { backgroundColor: "#2b3124" },
  tabText: { fontSize: 14, color: "#6f7c5d" },
  tabTextActive: { color: "#fff", fontWeight: "600" },
  chips: { marginBottom: 15 },
  chip: {
    padding: 10,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e4e8da",
    borderRadius: 8,
    marginRight: 7,
  },
  chipActive: { backgroundColor: "#fff0b5", borderColor: "#e5cf70" },
  demo: { fontSize: 12, color: "#8b947c", marginBottom: 15 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 13,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#e1e6d7",
    marginBottom: 19,
  },
  postPadding: { padding: 17 },
  author: { fontSize: 13, fontWeight: "600", color: "#74825f" },
  postTitle: {
    fontSize: 19,
    fontWeight: "700",
    lineHeight: 29,
    marginVertical: 11,
    color: "#2a3021",
  },
  meta: { fontSize: 12, color: "#94a07f" },
  image: { width: "100%", aspectRatio: 1.2 },
  textPost: {
    fontSize: 21,
    lineHeight: 35,
    padding: 26,
    backgroundColor: "#fff3c5",
    color: "#383e2b",
  },
  actions: { padding: 12, flexDirection: "row", gap: 12, alignItems: "center" },
  action: { fontSize: 15, padding: 6, color: "#71815a" },
  voted: { color: "#987107", fontWeight: "800" },
  saveAction: { marginLeft: "auto" },
  empty: {
    padding: 35,
    textAlign: "center",
    fontSize: 15,
    lineHeight: 25,
    color: "#7c8b67",
  },
  error: { color: "#ac4230", fontSize: 14, padding: 15 },
  more: {
    padding: 18,
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 8,
  },
  bottomBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    padding: 9,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#e4e8dc",
  },
  bottomText: { fontSize: 14, color: "#92a07f" },
  bottomActive: { color: "#343f26", fontWeight: "700" },
  compose: {
    backgroundColor: "#ffdb55",
    width: 48,
    height: 43,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
  },
  composeText: { fontSize: 29 },
  modalHeader: {
    padding: 21,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: { fontSize: 24, fontWeight: "800", color: "#2d3523" },
  close: { fontSize: 31, color: "#81936a" },
  modalBody: { padding: 21, paddingBottom: 50 },
  description: {
    fontSize: 16,
    lineHeight: 26,
    color: "#879572",
    marginBottom: 20,
  },
  button: {
    backgroundColor: "#ffdb55",
    borderRadius: 9,
    padding: 15,
    alignItems: "center",
    marginVertical: 12,
  },
  buttonText: { fontSize: 16, fontWeight: "700", color: "#343b29" },
  textarea: { minHeight: 110, textAlignVertical: "top", marginTop: 15 },
  switchAuth: {
    textAlign: "center",
    fontSize: 14,
    marginTop: 14,
    color: "#8d7e3b",
  },
  comment: {
    borderBottomWidth: 1,
    borderColor: "#e3e8d9",
    paddingVertical: 16,
  },
  commentBody: { fontSize: 16, lineHeight: 26, marginTop: 9, color: "#37452b" },
});
