source "https://rubygems.org"
ruby ">= 3.2.0"
gem "rails", "~> 8.1.0"
# Rails 8.1 passes positional options to JSON.parse; JSON 3 requires keywords.
gem "json", "~> 2.0"
gem "pg", "~> 1.5"
gem "puma", ">= 6.0"
gem "bcrypt", "~> 3.1"
gem "rack-cors", "~> 3.0"
gem "rack-attack", "~> 6.8"
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.3"
gem "image_processing", "~> 1.14"
gem "aws-sdk-s3", "~> 1.0", require: false
group :development, :test do
  gem "brakeman", require: false
end
